Adds basic structure of counter
dmitriyrotaenko/fe-learning pull request #1
Opened 2024-08-16 16:19 UTC by dmitriyrotaenko

2024-08-17 12:21 UTC, zavsievich commented
Пожалуйста, добавь github-pages, чтобы можно было потыкать результат 

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site

2024-08-17 12:35 UTC, zavsievich requested changes
Отличная работа, молодец! Ты хорошо поработал с вёрсткой и джаваскриптом. Никаких серьёзных недочётов нет. Сделай, пожалуйста, github-pages, резолвни комменты и я аппрувну МР

2024-08-17 12:35 UTC, zavsievich commented on counter/index.html
Отлично поработал с БЭМом и вёрсткой!

2024-08-17 12:35 UTC, zavsievich commented on counter/index.html
> +			<span class="counter__value"></span>
Следует ли добавить дефолтное значение, чтобы юзер видел что-то до того, как js отработает?

2024-08-17 12:35 UTC, zavsievich commented on counter/main.js
> +	if(counterValue === 0) return;
В требованиях не было пункта о том, что счётчик не может быть меньше 0. Давай удалим эту проверку

2024-08-17 12:35 UTC, zavsievich commented on counter/styles.css
> +@media screen and (width >= 720px) {
При увеличении браузерного шрифта, значения в пикселях не будут под него подстраиваться, из-за чего размеры будут выглядеть непропорционально. Раз уж начали юзать REM-ы, давай и тут заменим

2024-08-17 12:35 UTC, zavsievich commented on counter/styles.css
> +	gap: 5px;
Хорошим тоном во фронтенде и в дизайне считается использование значений, кратных 4. Замени, пожалуйста, и давай в будущем придерживаться таких значений

2024-08-17 13:35 UTC, dmitriyrotaenko commented on counter/index.html
> +			<span class="counter__value"></span>
С учётом текущих требований, можно поставить `0`, так как это всегда начальное значение

2024-08-17 13:42 UTC, dmitriyrotaenko commented on counter/styles.css
> +	gap: 5px;
Понял, поправляю. А почему так?

2024-08-17 13:44 UTC, zavsievich commented on counter/styles.css
> +	gap: 5px;
Вот тут можно почитать о том, чем хороша кратная 4 сетка

https://ux.pub/editorial/proshchai-sietka-8-pt-priviet-sietka-4-pt-1eb3

2024-08-17 13:55 UTC, dmitriyrotaenko commented on counter/styles.css
> +@media screen and (width >= 720px) {
Не понимаю, как это работает.

Посмотрел, как ведёт себя брейк поинт при указании в `rem` (720px = 45rem). Разница есть, но логика не понятна.

Если я увеличиваю базовый размер шрифта до `24px` (вместо 16), то медиа квери срабатывает на ширине вьюпорта в ~ `1080px`, а это `67.5rem`.

2024-08-19 22:17 UTC, zavsievich commented on counter/styles.css
> +@media screen and (width >= 720px) {
сохранил вопрос на обсудить

2024-08-19 22:19 UTC, zavsievich commented on counter/styles.css
> +	gap: 4px;
Так как начали использовать ремы, давай использовать их во всех местах. Поправь, пожалуйста, и можно мержить

2024-08-19 22:21 UTC, zavsievich commented on counter/styles.css
> +	gap: 4px;
```suggestion
	gap: 0.25rem;
```

2024-08-20 07:44 UTC, merged