Adds improvements to app layout and styling
dmitriyrotaenko/fe-learning pull request #2
Opened 2024-08-22 18:21 UTC by dmitriyrotaenko

This PR tries to accomplish the following tasks:

- [x] Не очень красиво у нас выглядят кнопки: давай сделаем их более красивыми. Давай возьмем кнопку под номером 45: https://getcssscan.com/css-buttons-examples
- [x] Браузерные шрифты — это хорошо, но хочется что-то кастомное. Давай подключим Roboto Slab шрифт из Google fonts и будем использовать его для всего нашего приложения
- [ ] Надо сделать сохранение пользовательского счётчика: давай сохранять в куки текущее значение счётчика и если в куке есть значение, то будем доставать его оттуда, иначе показывать 0
- [x] У нас должна быть кнопка reset, которая позволит обнулять счётчик. Она должна находиться под всеми кнопками и должна быть отделена от них чертой
- [x] Хочется как-то выделить количество раз, которое ты кликнул. Значение счётчика должно быть жирностью 900. 
- [ ] Если счётчик больше 0, то его значение должно быть цвета green
- [ ] В значении 0 счётчик должен быть цвета gray
- [ ] Если счётчик заходит в отрицательные значения, то его цвет должен быть tomato
- [x] Мы должны показывать футер, в котором должна быть информация о том, что приложение разработано тобой и указан текущий год. Футер должен быть прибит к низу страницы

2024-08-22 18:38 UTC, dmitriyrotaenko commented
@zavsievich посмотри PR, пожалуйста

2024-08-22 20:44 UTC, zavsievich requested changes
Очень хорошая работа! Благодаря мелким улучшениям можем сделать наши стили более устойчивыми к изменениям и доработкам в будущем

2024-08-22 20:44 UTC, zavsievich commented on counter/index.html
> +					<button class="counter__reset btn">Reset</button>
Если мы почему-то решим сначала выводит резет, а потом кнопки, то придётся менять классы. Совет: название классов не должно быть завязано на расположение элементов

2024-08-22 20:44 UTC, zavsievich commented on counter/index.html
> +				<div class="counter__btns__first-line">
`counter__btns__first-line` -- у тебя сломался БЭМ. Так как у них одинаковые стили, то можно назвать их одинаково. Например, 

```suggestion
				<div class="counter__wrap">
```

2024-08-22 20:44 UTC, zavsievich commented on counter/index.html
> +				<div class="counter__btns__second-line">
```suggestion
				<div class="counter__wrap">
```

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +}
Хорошая практика: всем элементам (и псевдо в том числе) всегда устанавливать border-box. Вот статья о боксовой модели -- это одна из главных вещей, которые нужно понимать в CSS: https://piccalil.li/blog/the-box-model-and-box-sizing/

```suggestion
*,
*::before,
*::after { 
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}
```

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +  font-family: 'Roboto Slab', sans-serif;
Молодец, что поставил sans-serif фоллбэк!

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +  box-sizing: border-box;
это уже не надо

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +  line-height: 2.09rem;
line-height всегда лучше устанавливать в безразмерных величинах, чтобы при изменении размера шрифта или при наследовании сохранять line-height относительно шрифта

https://allthingssmitty.com/2017/01/30/nope-nope-nope-line-height-is-unitless/

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +}
Давай сделаем нашей кнопке красивый outline какой-нибудь, чтобы он был хорошо виден при фокусе

https://www.erwinhofman.com/blog/fancy-flexible-css-outlines-help-web-accessibility/

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
> +}
Контейнеры у кнопок должны вести себя одинаково, поэтому можно давать им один класс

2024-08-22 20:44 UTC, zavsievich commented on counter/styles.css
>  	}
Почему ты устанавливаешь hover только для больших экранов?

2024-08-24 16:59 UTC, dmitriyrotaenko commented on counter/styles.css
>  	}
Обсудили

2024-08-24 18:02 UTC, dmitriyrotaenko commented
@zavsievich пофиксил комменты

2024-08-27 18:42 UTC, zavsievich requested changes
Последний момент с БЭМ-наименованием. 

https://ru.bem.info/methodology/faq/#%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BD%D0%B5-%D1%81%D1%82%D0%BE%D0%B8%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-block__elem1__elem2

2024-08-27 18:42 UTC, zavsievich commented on counter/styles.css
> +  Насколько ок завязывать логику стилей на их расположение в CSS файле?
Так работает css: стили ниже более приоритетны, поэтому это нормально

2024-08-27 18:42 UTC, zavsievich commented on counter/index.html
> +				<div class="counter__btns__wrapper">
Последний коммент и можно мержить: у БЭМ-элементов не может быть своих элементов. Назови класс так, чтобы он соответствовал БЭМ-методологии

2024-08-27 21:48 UTC, dmitriyrotaenko commented on counter/index.html
> +				<div class="counter__btns__wrapper">
counter__wrapper

2024-08-27 21:57 UTC, zavsievich commented on counter/index.html
> +				<div class="counter__btns__wrapper">
Да, подходит 👍

2024-08-28 17:28 UTC, merged