Add dynamic colors to counter
dmitriyrotaenko/fe-learning pull request #3
Opened 2024-08-28 19:07 UTC by dmitriyrotaenko

ПР пробует решить следующие задачи:

- [x] ~~Не очень красиво у нас выглядят кнопки: давай сделаем их более красивыми. Давай возьмем кнопку под номером 45: https://getcssscan.com/css-buttons-examples~~
- [x] ~~Браузерные шрифты — это хорошо, но хочется что-то кастомное. Давай подключим Roboto Slab шрифт из Google fonts и будем использовать его для всего нашего приложения~~
- [ ] ~~Надо сделать сохранение пользовательского счётчика: давай сохранять в куки текущее значение счётчика и если в куке есть значение, то будем доставать его оттуда, иначе показывать 0~~
- [x] ~~У нас должна быть кнопка reset, которая позволит обнулять счётчик. Она должна находиться под всеми кнопками и должна быть отделена от них чертой~~
- [x] Хочется как-то выделить количество раз, которое ты кликнул. Значение счётчика должно быть жирностью 900. 
- [x] Если счётчик больше 0, то его значение должно быть цвета green
- [x] В значении 0 счётчик должен быть цвета gray
- [x] Если счётчик заходит в отрицательные значения, то его цвет должен быть tomato
- [ ] Мы должны показывать футер, в котором должна быть информация о том, что приложение разработано тобой и указан текущий год. Футер должен быть прибит к низу страницы

2024-08-28 19:08 UTC, dmitriyrotaenko commented
@zavsievich посмотри МР пожалуйста

2024-08-28 20:04 UTC, zavsievich requested changes
Отлично, мы начинаем добавлять динамичность! Давай попробуем немного упростить алгоритм

2024-08-28 20:04 UTC, zavsievich commented on counter/styles.css
> +}
давай придерживаться классической БЭМ-нотации для модификаторов:
```suggestion
.counter__value.counter__value--zero {
  color: gray;
}

.counter__value.counter__value--positive {
  color: green;
}

.counter__value.counter__value--negative {
  color: tomato;
}
```

2024-08-28 20:04 UTC, zavsievich commented on counter/main.js
> +}
Написанный алгоритм читать сложновато: мы одновременно делаем тоггл для трёх классов по разным условиям. Мне кажется, ментальную модель можно построить проще: ты сетишь то значение, которое удовлетворяет какому-то условию. Попробуй сделать не через классы, а устанавливать значение data-атрибуту

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

2024-08-28 21:10 UTC, dmitriyrotaenko commented on counter/main.js
> +}
"ты сетишь то значение, которое удовлетворяет какому-то условию", а этого достаточно? Насколько я понимаю, у нас всегда должен быть 1 класс. То есть ситуации, где ZERO_VALUE_CSS + POSITIVE_VALUE_CSS классов быть не должно.

И если я сетаю 1 значение, я должен убирать два других, не подходящих по условию

2024-08-28 21:14 UTC, dmitriyrotaenko commented on counter/main.js
> +}
И по этому моменту вопрос:

> Попробуй сделать не через классы, а устанавливать значение data-атрибуту

То есть мы избавляемся от классов и сетаем цвета как-то по дата атрибут селектору в CSS? Такая идея?

2024-08-30 07:24 UTC, dmitriyrotaenko commented
@zavsievich завязал смену цвета на изменения дата аттрибута

2024-08-30 23:03 UTC, zavsievich commented on counter/styles.css
> +} */
Удали комменты, пожалуйста, если они не нужны

2024-08-31 07:44 UTC, merged