Add cookie and footer
dmitriyrotaenko/fe-learning pull request #4
Opened 2024-09-05 19:41 UTC by dmitriyrotaenko

ПР пробует решить следующие задачи:

- [x] ~~Не очень красиво у нас выглядят кнопки: давай сделаем их более красивыми. Давай возьмем кнопку под номером 45: https://getcssscan.com/css-buttons-examples~~
- [x] ~~Браузерные шрифты — это хорошо, но хочется что-то кастомное. Давай подключим Roboto Slab шрифт из Google fonts и будем использовать его для всего нашего приложения~~
- [x] Надо сделать сохранение пользовательского счётчика: давай сохранять в куки текущее значение счётчика и если в куке есть значение, то будем доставать его оттуда, иначе показывать 0
- [x] ~~У нас должна быть кнопка reset, которая позволит обнулять счётчик. Она должна находиться под всеми кнопками и должна быть отделена от них чертой~~
- [x] ~~Хочется как-то выделить количество раз, которое ты кликнул. Значение счётчика должно быть жирностью 900.~~
- [x] ~~Если счётчик больше 0, то его значение должно быть цвета green~~
- [x] ~~В значении 0 счётчик должен быть цвета gray~~
- [x] ~~Если счётчик заходит в отрицательные значения, то его цвет должен быть tomato~~
- [x] Мы должны показывать футер, в котором должна быть информация о том, что приложение разработано тобой и указан текущий год. Футер должен быть прибит к низу страницы

2024-09-05 19:41 UTC, dmitriyrotaenko commented
@zavsievich посмотри МР пожалуйста

2024-09-05 20:58 UTC, zavsievich requested changes
Молодец, ты хорошо справился! Давай поправим пару моментов и можно мержить:)

2024-09-05 20:58 UTC, zavsievich commented on counter/cookieManager.js
> +function getCookie(name) {
Предлагаю переименовать эту функцию, чтобы было понятно, о чем идёт речь
```suggestion
function getCookieValueByName(name) {
```

2024-09-05 20:58 UTC, zavsievich commented on counter/cookieManager.js
> +	document.cookie = newCookie;
Этой строчкой ты удаляешь все куки и сетишь только одно значение. Попробуй взять старую строку, добавить в неё новую и вернуть всё значение

2024-09-05 20:58 UTC, zavsievich commented on counter/cookieManager.js
> +	for(let attr in attributes) {
Так как здесь attr не меняется, давай использовать const. Правило довольно примитивное: всегда используй const, а если надо менять значение, то let

P.S. Возможно, стоит подумать о том, что если тебе нужен let, то можно изменить реализацию так, чтобы можно было использовать const

2024-09-05 20:58 UTC, zavsievich commented on counter/index.html
> +	<script defer src="./main.js"></script>
Так как скрипты у тебя лежат внизу, то браузер дойдет до них только после того, как распарсит всё дерево. Атрибуты async и defer были добавлены как раз для того, чтобы можно было скачивать скрипты до того, как твоё DOM-дерево распаршено

2024-09-05 20:58 UTC, zavsievich commented on counter/main.js
> +footerDate.innerText = getYear();
Так как функция getYear довольно простая и пока что больше нигде не используется, мы можем удалить её и сразу сюда прокидывать вычисленное значение

2024-09-07 10:14 UTC, dmitriyrotaenko commented on counter/cookieManager.js
> +	document.cookie = newCookie;
Я не уверен, что понял проблему.

`document.cookie` работает как сеттер и геттер. Если ему передать строку в которой есть name (path, domain) то он или засетает такую куку или перепишет. Остальные куки он не трогает

2024-09-07 10:26 UTC, zavsievich commented on counter/cookieManager.js
> +	document.cookie = newCookie;
Супер!

2024-09-07 10:27 UTC, zavsievich commented on counter/index.html
> +	<script defer src="./main.js"></script>
А почему ты удалил defer атрибуты?

2024-09-07 10:31 UTC, dmitriyrotaenko commented on counter/index.html
> +	<script defer src="./main.js"></script>
Как будто и без них работает

2024-09-07 10:33 UTC, zavsievich commented on counter/index.html
> +	<script defer src="./main.js"></script>
Оно-то работает, но твои скрипты начинают скачиваться только после того, как распарсится DOM. Как можно сделать так, чтобы мы скачали скрипты до всей DOM работы?

2024-09-07 10:33 UTC, dmitriyrotaenko commented on counter/index.html
> +	<script defer src="./main.js"></script>
То есть он загружает, парсит, выполняет тогда, когда дойдет. К этому моменту дерево будет готово

2024-09-07 10:35 UTC, dmitriyrotaenko commented on counter/index.html
> +	<script defer src="./main.js"></script>
Аттрибутами defer и async. В нашем случае defer подойдет, потому что важен порядок скриптов.

Но у меня сразу вопрос. Скачивание !== парсинг и выполнение скриптов ведь?

2024-09-07 12:44 UTC, zavsievich commented on counter/index.html
> +	<script defer src="./main.js"></script>
Всё верно, defer не вызовет ошибок. Ты описал работу async. Пожалуйста, поправь ПР

2024-09-07 14:51 UTC, merged