Moves counter to separate class
dmitriyrotaenko/fe-learning pull request #5
Opened 2024-09-07 20:14 UTC by dmitriyrotaenko

Что сделал в МРе:

- Вынес каунтер в отдельный класс `Counter`.
- Вынес структуру каунтера в отдельный JS объект.
- Добавил функцию построения дерева для каунтера.

P.S. некоторые части кода оставил закомменченными для себя 
P.S.S большую часть строка занимает дерево. Тестил, в текущем варианте обход работает, можно создать сколько хочешь деревьев.

2024-09-07 20:42 UTC, zavsievich commented
Пожалуйста, сделай МР в этот МР, в котором ты покажешь, как создаются другие счётчики

P.S. Скрипты всё ещё находятся снизу и начинают загружаться только после полного парсинга DOM

2024-09-07 20:50 UTC, dmitriyrotaenko commented
@zavsievich 

Я не понимаю что мне нужно сделать. Добавить скрипты наверх? (

> Скрипты всё ещё находятся снизу и начинают загружаться только после полного парсинга DOM

И это:

> Пожалуйста, сделай МР в этот МР, в котором ты покажешь, как создаются другие счётчики

МР в МР? В гугле не нашёл такого

Если что, счетчики создаются вот так:

```js
const initialCounter = new Counter(document.querySelector('.counters'));
const anotherCounter = new Counter(document.querySelector('.counters'));
```

2024-09-07 20:51 UTC, zavsievich requested changes
С этим МРом ты полностью ломаешь функциональность нашего приложения. Каждый МР должен приближать нас к выполнению бизгнс-целей и не ломать текущую функциональность

2024-09-07 20:51 UTC, zavsievich commented on counter/Counter.js
> +				type: 'dev',
Кажется, тут опечатка
```suggestion
				type: 'div',
```

2024-09-07 20:53 UTC, zavsievich commented
> @zavsievich 
> 
> 
> 
> Я не понимаю что мне нужно сделать. Добавить скрипты наверх? (
> 
> 
> 
> > Скрипты всё ещё находятся снизу и начинают загружаться только после полного парсинга DOM
> 
> 
> 
> И это:
> 
> 
> 
> > Пожалуйста, сделай МР в этот МР, в котором ты покажешь, как создаются другие счётчики
> 
> 
> 
> МР в МР? В гугле не нашёл такого
> 
> 
> 
> Если что, счетчики создаются вот так:
> 
> 
> 
> ```js
> 
> const initialCounter = new Counter(document.querySelector('.counters'));
> 
> const anotherCounter = new Counter(document.querySelector('.counters'));
> 
> ```

1. Да, добавить в head

2. Да, МР в МР. При создании МРа ты делаешь target branch не main, а текущую ветку

2024-09-07 21:05 UTC, dmitriyrotaenko commented
Я поправлю текущий МР

2024-09-07 21:54 UTC, dmitriyrotaenko commented
Поправил МР. Сейчас работает как раньше, только без сохранения в куки

2024-09-17 14:26 UTC, zavsievich commented
@dmitriyrotaenko у меня к этому МРу есть несколько вопросов, которые хотелось бы понять прежде, чем двигаться дальше
1. Почему ты решил сделать реализацию через классы? Чем это решение лучше, чем просто вызывать функции, например? Я вижу использование статических и приватных полей и не понимаю, зачем они здесь
2. Ты создаёшь логику, которая будет строить HTML из тобою написанного объекта, у которого нет никаких правил и спецификации и в котором можно легко ошибиться -- вот пример: https://github.com/dmitriyrotaenko/fe-learning/pull/5#discussion_r1748943311. ИМХО с HTML проще всего работать с помощью HTML. Можно ли как-то проще создать разметку счётчика и среднерить его в браузере?
3. К сожалению, мы не можем ломать текущую функциональность: если у нас уже была логика сохранения значения в куках, значит, и после релиза она должна работать

2024-09-17 15:34 UTC, dmitriyrotaenko commented
> Почему ты решил сделать реализацию через классы? Чем это решение лучше, чем просто вызывать функции, например?

Я не могу сказать, что это решение лучше или хуже. Идея класса как темплейта для объектов каунтера — первое о чём я подумал. Если мне необходимы инстансы чего-то, почему не использовать класс, который для этого и создан?

> Я вижу использование статических и приватных полей и не понимаю, зачем они здесь

Статическая переменная хранит в себе дерево каунтера. Это что-то, что больше принадлежит классу, чем определённому инстансу. Приватные методы — они работаю только внутри класса и напрямую их не нужно вызывать. Неприватные методы оставил такими на случай, если нужна будет апишка к классу.

> ИМХО с HTML проще всего работать с помощью HTML. Можно ли как-то проще создать разметку счётчика и среднерить его в браузере?

Можно работать с HTML строкой через `innerHTML`, но насколько я знаю, это небезопасно. 

> Ты создаёшь логику, которая будет строить HTML из тобою написанного объекта, у которого нет никаких правил и спецификации

А о каких правилах и спецификации речь?

> К сожалению, мы не можем ломать текущую функциональность: если у нас уже была логика сохранения значения в куках, значит, и после релиза она должна работать

Сейчас каунтер работает как и раньше, в том числе есть сохранение в куки

2024-09-18 07:49 UTC, zavsievich commented
1. Да, это и правда не лучше и не хуже, но посмотри в следующие ответы и тогда попробуй решить, нужны ли будут тебе классы в данном случае

2. Изменится ли как-то твоя реализация, если ты конвертнешь свои статические и приватные поля в обычные?

3. Посмотри на template: возможно, он лучше подходит в данном сценарии. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

4. Ну вот есть спека HTML с правилами и ограничениями. Есть ли правила, по которым формируется твой объект? Как в нём прописываются атрибуты, сетятся обработчики событий? Ты можешь легко нагуглить, как что-то сделать в HTML. Повторяет ли твоя реализация все API, которые в нем есть? Совет: для обучения изобретать свои велосипеды неплохо, но, скорее всего, твои велосипеды не будут иметь спецификации и туториалов, как ими пользоваться. Поэтому лучше использовать нативные инструменты по максимуму

5. Супер!

2024-09-20 19:03 UTC, zavsievich approved these changes
Отличная работа, молодец! Можешь мержить

2024-09-20 19:28 UTC, merged